### PR TITLE
Hi I added some things xD

### PR DESCRIPTION
**Pull request by ryanfox1985**
I added Rspec test.
Fixed rubocop config.

### CODE REVIEW

**Comment by ryanfox1985** [comment]
Now travisCI check the commits xD good!
Please execute rake and open coverage/index.html.

**Comment by ryanfox1985** [comment]
Some offenses from rubocop accept auto-correct xD.

**Comment by leikind** [comment]
Tell me, why do you believe everything Rubocop tells you is the ultimate truth? This is some kind of cargo cult you are blindly following. Some rules it insists on are stupid and brain damaged

**Comment by leikind** [comment]
for example it wants to autocorrect my code like this:

```
  row_content = if replace_row_output
    no_rightmost_column = true
    replace_row_output
  else
    row_content, tmp_cell_value_of_the_ordered_column = get_row_content(rendering,ar,sorting_dependant_row_cycling)
    cell_value_of_the_ordered_column = tmp_cell_value_of_the_ordered_column if tmp_cell_value_of_the_ordered_column
    row_content
                end

```

Or it insists on not naming methods like "has_xyq?"

How the hell does it help? What kind of idiocy is it?

I am merging your commits, and then I will revert the rubocop config back to my version. I ain't following no cargo cult religions.

**Pull request merged**
