### PR TITLE
Rails3

### PR DESCRIPTION
**Pull request by dima4p**
Use of ActiveRecord::Relation is needed for cancan gem

### CODE REVIEW

**Comment by dima4p** [comment]
I do not know why, but I asked to make commits not to master but to rails3 branch

**Comment by dima4p** [comment]
maybe the reason is I've cloned first the master branch

**Comment by leikind** [comment]
No problem, I understand to which branch it should to be applied.
This was coming, I will test it and apply as soon as I can.

**Comment by leikind** [comment]
Merged: https://github.com/leikind/wice_grid/commit/73739c9a1394632217b6f2a81804b3631d6f6124

Thanks, шлите ещё  :)

Closing

**Pull request closed without merging**
