### PR TITLE
Fixed offense array.

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hi again xD.

### CODE REVIEW

**Comment by leikind** [comment]
What is an offense array?

**Comment by ryanfox1985** [comment]
yes, the standard is %w(a b c)

2015-10-17 20:46 GMT+02:00 Yuri Leikind notifications@github.com:

**Comment by leikind** [comment]
what is the point of this commit?

**Comment by ryanfox1985** [comment]
xD I fixed a Rubocop offense.
Well recently I update your gem and it's great. Goood job.

Regards.

2015-10-17 22:50 GMT+02:00 Yuri Leikind notifications@github.com:

**Comment by leikind** [comment]
This project is in need of real work and real changes, and replacing `['a', 'b']` by `%w(a b)` is not what this project needs, it solves 0 problems. I will not accept such pull requests. This is not a contribution.

**Comment by ryanfox1985** [comment]
mmmm you doesn't remember that I added Rubocop, TDD with Rspec and the
readme? Travis etc.

2015-10-17 23:19 GMT+02:00 Yuri Leikind notifications@github.com:

**Comment by leikind** [comment]
I do remember. And I have always been against using all Rubocop cops. This is silly. This is not software development. This is masturbation.

Software development is adding features, improving featurs, fixing bugs. This project is is need of these. It doesn't need 100500 commits to replace `['a', 'b', 'c']` by `%w(a b c)` to conform to some braindead code standards.

**Comment by ryanfox1985** [comment]
Which editor you use editor you use to develop RoR? Rubymine also detect
this.

2015-10-17 23:28 GMT+02:00 Yuri Leikind notifications@github.com:

**Comment by leikind** [comment]
You are confusing a tool for a goal. Rubymine, rubocop, CI, and so on are tools. They are not goals.

**Comment by ryanfox1985** [comment]
Well tell me what is the roadmap? I interested to contribute to your
library.

2015-10-17 23:35 GMT+02:00 Yuri Leikind notifications@github.com:

**Comment by leikind** [comment]
https://github.com/leikind/wice_grid/issues?q=is%3Aopen+is%3Aissue+label%3A%22to+do%22

**Pull request closed without merging**
