### PR TITLE
fix deprecation warning

### PR DESCRIPTION
**Pull request by bvogel**
fix for #301

### CODE REVIEW

**Comment by leikind** [comment]
Thank you, I appreciate this contribution! 👍

**Comment by noahc** [comment]
Do you have plans to release this to ruby gems or should I point my project to the rails3 branch?

**Comment by leikind** [comment]
@noahc   https://rubygems.org/gems/wice_grid/versions/3.6.1

**Comment by leikind** [comment]
@noahc oops. It's a broken build

```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: actionview requires activesupport (= 4.2.6); railties requires activesupport (= 5.0.0.rc1); kaminari requires activesupport (>= 3.0.0); actionpack requires activesupport (= 5.0.0.rc1), rack (~> 2.x), actionview (= 5.0.0.rc1); rails-dom-testing requires activesupport (< 5.0, >= 4.2.0.beta); rails-deprecated_sanitizer requires activesupport (>= 4.2.0.alpha); activerecord requires activesupport (= 4.2.6); activemodel requires activesupport (= 4.2.6)
```

**Comment by leikind** [comment]
unpublished 3.6.1

**Comment by noahc** [comment]
Thanks! 

Saw 3.6.2 was live.

**Comment by leikind** [comment]
it was my local error. It should be fine

On Wed, Jun 15, 2016 at 9:34 PM, Noah Clark notifications@github.com
wrote:

> Thanks!
> 
> Saw 3.6.2 was live.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/leikind/wice_grid/pull/302#issuecomment-226295627,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAGDwmrPhM23N5bqEQOMYFNr6rqKE71vks5qMFO1gaJpZM4Iz24p
> .

## 

Best regards,
Yuri Leikind

Sent from my Nokia 3310

**Pull request merged**
