### PR TITLE
Append default actions

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hi I created a new variable with the defaults actions new, edit, delete.

also you can configure the grid:
<%= grid(@array, {append_actions: [:edit, :delete]}) do |g|....
<%= grid(@array, {append_actions: []}) do |g|....

Regards.

### CODE REVIEW

**Comment by ryanfox1985** [comment]
mmm I missed the translations of show, edit, delete.

**Comment by leikind** [comment]
Adding buttons has never been a goal of WiceGrid. A developer can add such a column in a minute. There is absolutely no  point in adding this API, it only leads to unnecessary API boat.

**Comment by ryanfox1985** [comment]
I'm starting with your library. I need so time to understand.

I haven't finished yet. This small develop simplifies my grids xD.

Regards.

**Comment by leikind** [comment]
not accepting unnecessary API bloat

**Pull request closed without merging**
