### PR TITLE
add CSV (output) encoding configuration

### PR DESCRIPTION
**Pull request by bvogel**
Our users use the Microsoft Excel and the current output UTF-8 wouldn't work.

### CODE REVIEW

**Comment by leikind** [comment]
Thank you for this, but would you please mention this feature in README?

**Comment by bvogel** [comment]
like so?

**Comment by leikind** [comment]
Thanks a lot! ♡

**Comment by bvogel** [comment]
Thank you for the tool. How is your release schedule for 3.6.0?

**Comment by leikind** [comment]
Unfortunately I have almost no time for this gem. I have no idea :-(

**Comment by leikind** [comment]
s/ to this gem/ for this gem/

On Fri, Nov 27, 2015 at 10:16 AM, Yuri Leikind <yuri.leikind@gmail.com>
wrote:

> Unfortunately I have almost no time to this gem. I have no idea :-(
>
> On Fri, Nov 27, 2015 at 9:34 AM, Burkhard Vogel <notifications@github.com>
> wrote:
>
>> Thank you for the tool. How is your release schedule for 3.6.0?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/leikind/wice_grid/pull/265#issuecomment-160068730>.
>>
>
>
>
> --
> Best regards,
> Yuri Leikind
>
> Sent from my Nokia 3310
>



-- 
Best regards,
Yuri Leikind

Sent from my Nokia 3310

**Comment by bvogel** [comment]
I completely understand... could you find time to package "as is" as 3.6.0.pre4? If not, no worries we'll use the rails3 branch as source...

**Comment by leikind** [comment]
That I can do :)
This weekend

On Fri, Nov 27, 2015 at 10:25 AM, Burkhard Vogel notifications@github.com
wrote:

> I completely understand... could you find time to package "as is" as
> 3.6.0.pre4? If not, no worries we'll use the rails3 branch as source...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/leikind/wice_grid/pull/265#issuecomment-160088854.

## 

Best regards,
Yuri Leikind

Sent from my Nokia 3310

**Comment by bvogel** [comment]
Thank you, have a nice one...

**Comment by leikind** [comment]
https://rubygems.org/gems/wice_grid/versions/3.6.0.pre5

**Pull request merged**
