### PR TITLE
Fixed readme and translations

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hi again,

I fixed some mistakes in Spanish translations and in Readme the require bootstrap-datepicker library.

Regards.

### CODE REVIEW

**Comment by leikind** [comment]
The plugin can work with both jquery.ui.datepicker and bootstrap-datepicker, so this giving an example of how to use one and ignoring the other is not a fix. Both variants should be given.

**Comment by leikind** [comment]
If you split your commit into two I would merge your language fixes right away. I appreciate this!

**Comment by ryanfox1985** [comment]
Hi

I added the both examples.

Regards.

**Comment by leikind** [comment]
Thanks!

**Pull request merged**
