### PR TITLE
Make rubo cop not fail

### PR DESCRIPTION
**Pull request by noahc**
WIP

Trying to fix all Rubocop warnings. Will Continue working on this tomorrow.

### CODE REVIEW

**Comment by leikind** [comment]
You are wasting your time on useless things

**Comment by noahc** [comment]
Would it be better to remove Rubocop then? 

I'm trying to clean up the edges around the test output so my self and others can have increased confidence in a code base we're unfamiliar with. I agree that these changes aren't that significant, but they are the first small steps in getting the code base to a point where those unfamiliar with the code base can work with it with confidence. 

Do you disagree?

**Comment by leikind** [comment]
If wouldn't object to removing Rubocop.

**Comment by jdickey** [comment]
How about, instead, just creating a `.rubocop.yml` file that disables the cops you don't (yet) care about?

I've found on a couple of dozen projects (and counting) that RuboCop is one of my three or four pieces of dead-finger tech (along with Flog, Flay, Reek, and Inch). YMMV, but I just thought I'd put in a word.

**Comment by leikind** [comment]
I am not spending my time on this useless pursuit.

**Pull request merged**
