### PR TITLE
Replaced README.rdoc to README.md

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hi,

this is the initial commit, needs to be refactored.

Regards.

### CODE REVIEW

**Comment by ryanfox1985** [comment]
Here you can see:
https://github.com/ryanfox1985/wice_grid/tree/development

**Comment by leikind** [comment]
Please pay attention to lost markup. Search for +sometext+, and look at the text before Intro. It is broken

**Comment by ryanfox1985** [comment]
Yes xD I need so time.

**Comment by ryanfox1985** [comment]
what do you think now?

**Comment by leikind** [comment]
Better 
But the header is not what we had in README.rdoc. Look at the section before https://github.com/leikind/wice_grid

Also, look at section "Bug reports" attentively.

And the last thing: will it work with rake rdoc ?  I doubt. I like to generate docs locally. Is there an alternative?

**Comment by ryanfox1985** [comment]
Hi,

I added yard.
Now generate the doc at ./doc folder.
Take a look and tell me what do you think.

Needs some refactors.
Regards.

**Comment by leikind** [comment]
I appreciate your work, but could you please do this based on the latest version of the README and CHANGELOG?

**Comment by ryanfox1985** [comment]
Check now.

**Comment by leikind** [comment]
You write

---

  This adds the config files:
- config/initializers/wice_grid_config.rb
- config/locales/wice_grid.yml
- app/assets/stylesheets/wice_grid.scss

---

YML and SASS are not config files! Please don't change the original text. Also, there is no `app/assets/stylesheets/wice_grid.scss` in https://github.com/leikind/wice_grid/tree/development

Unlike Github, Yardoc produces a pretty shitty output. Is there a way to have good yardoc output?

**Comment by ryanfox1985** [comment]
I modified this line.

The standard from Github is Markdown. 
Sorry for your unlike with Yardoc, your are free for change the look xD, I don't waste my time with this. 

I'm looking for add Rspec and test to your library.

Regards.

**Comment by ryanfox1985** [comment]
And you need some refactors in README.md, you have duplicated things, a lot of lines, a lot examples.

**Pull request merged**
