### PR TITLE
Making query respect uppercases present in table names (for legacy da…

### PR DESCRIPTION
**Pull request by ablancag**
…tabases).

Based on 3.2.1 since that's the version in use.

Signed-off-by: Alex Blanca alex.blanca@gmail.com

### CODE REVIEW

**Comment by leikind** [comment]
Hey

Sorry it has taken so long.

Can you please re-do this based on HEAD so that it can be merged automatically?

**Comment by leikind** [comment]
done
thanks

**Comment by leikind** [comment]
Your fix is PostgreSQL specific, doesn't respect other DBs and renders generated SQL invalid. I rolled back your change.

I myself have spent the last year using PostgreSQL and it was rather silly of me to accept the PR in the first pace, my bad

**Comment by ablancag** [comment]
Would you be interested if I found a way of detecting whether PostgreSQL is
the database in use or not?

Don't know yet if possible, but could work.

Alex B.

**Comment by leikind** [comment]
There is already this code somewhere deep in ActiveRecord for escaping table names in SQL commands

**Comment by ablancag** [comment]
Ah. Is there?

Let me see what I find and will let you know.

Regards,

Alex B.

**Pull request merged**
