### PR TITLE
Revised configs.

### PR DESCRIPTION
**Pull request by ryanfox1985**
Rubocop fails not affect to travis.
Removed extensions.
Added test.

### CODE REVIEW

**Comment by leikind** [comment]
i think I merged it already https://github.com/leikind/wice_grid/commits/development

btw I merged a branch into 'development' which changes the API and removes some ugly old code https://github.com/leikind/wice_grid/blob/development/CHANGELOG.md#360

**Comment by ryanfox1985** [comment]
Hey why you don't merge mi code?

**Comment by leikind** [comment]
Why do you push to a feature branch at all? Please don't. The branch to work on is development.

**Comment by leikind** [comment]
I am reverting your variable renaming in wice_grid_misc.rb. I wrote this code just the other day and I have my reasons to call that variable precisely this way. It has to do with the functionality I am adding, and not the immediate data types that you are seeing.

**Pull request merged**
